[package]
name = "dkls23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3"
bincode = { version = "2.0.0-rc.3" }
# TODO: update with git path later
# sl-mpc-mate = {git = "https://gitlab.com/com.silencelaboratories/sl-crypto", branch = "main", features =["nacl"]}
# sl-oblivious = {git = "https://gitlab.com/com.silencelaboratories/sl-crypto", branch = "main" }
sl-mpc-mate = { path = "../sl-crypto/crates/sl-mpc-mate", features =["nacl"]}
sl-oblivious = { path = "../sl-crypto/crates/sl-oblivious" }
digest = "0.10.7"
sha2 = "0.10.7"
k256 = {version = "0.13", features= ["ecdsa", "serde"]}
merlin = "3.0.0"
rand = "0.8"
rand_chacha = { version = "0.3" }
serde = {version = "1.0", features = ["derive"]}
rayon ="1"
serde_arrays = "0.1.0"
thiserror = "1"

[dev-dependencies]
hex ="0.4.3"
tokio = { version = "1", features = ["rt", "sync", "macros", "rt-multi-thread" ] }

[workspace]
members = [
  ".",
  "crates/dkls-party",
  "crates/msg-relay",
  "crates/msg-relay-svc",
  "crates/msg-relay-client",
  "wrapper/node"
]

[profile.release]
# lto = true
strip = "symbols"
# debug = true
