[package]
name = "dkls23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode.workspace = true
sl-mpc-mate.workspace = true
sl-oblivious.workspace = true
digest.workspace = true
sha2.workspace = true
k256 = { workspace = true, features= [ "ecdsa" ] }
merlin.workspace = true
rand.workspace = true
rand_chacha.workspace = true
rayon.workspace = true
thiserror.workspace = true
tracing.workspace = true
futures-util.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "macros" ] }

[dev-dependencies]
hex ="0.4.3"
tokio = { workspace = true, features = ["rt", "sync", "macros", "rt-multi-thread" ] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[workspace]
members = [
  ".",
  "crates/dkls-party",
  "crates/msg-relay",
  "crates/msg-relay-svc",
  "crates/msg-relay-client",
  # "wrapper/node",
  # "wrapper/wasm"
]

[workspace.dependencies]
bincode = "2.0.0-rc.3"
digest = "0.10.7"
sha2 = "0.10.7"
k256 = "0.13"
merlin = "3.0.0"
rand = "0.8"
rand_chacha = "0.3"
rayon ="1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = "1.32"
futures-util = "0.3.0"
anyhow = "1"
sl-mpc-mate  = { git = "https://gitlab.com/com.silencelaboratories/sl-crypto", branch = "stream-msg-relay" }
sl-oblivious = { git = "https://gitlab.com/com.silencelaboratories/sl-crypto", branch = "stream-msg-relay" }

[profile.release]
# lto = true
strip = "symbols"
# debug = true
