version: "3.8"

services:
  setup-coord:
    image: dkls-party
    command: |
      /usr/local/bin/msg-relay-svc
        --listen 0.0.0.0:8080
    environment:
      RUST_LOG: info
    ports:
      - 8080:8080

  p-1-1:
    image: dkls-party
    command: |
      /usr/local/bin/dkls-party serve
        --storage /data
        --party-key /run/secrets/party-1-sk
        --setup-vk-file /run/secrets/setup-vk
        --coordinator ws://setup-coord:8080/v1/msg-relay
    environment:
      RUST_LOG: info
    ports:
      - 8081:8080
    volumes:
      - p1-data:/data
    secrets:
      - setup-vk
      - party-1-sk

  p-2-1:
    image: dkls-party
    command: |
      /usr/local/bin/dkls-party serve
        --storage /data
        --party-key /run/secrets/party-2-sk
        --setup-vk-file /run/secrets/setup-vk
        --coordinator ws://setup-coord:8080/v1/msg-relay
    environment:
      RUST_LOG: info
    ports:
      - 8082:8080
    volumes:
      - p2-data:/data
    secrets:
      - setup-vk
      - party-2-sk

  p-3-1:
    image: dkls-party
    command: |
      /usr/local/bin/dkls-party serve
        --storage /data
        --party-key /run/secrets/party-3-sk
        --setup-vk-file /run/secrets/setup-vk
        --coordinator ws://setup-coord:8080/v1/msg-relay
    environment:
      RUST_LOG: info
    ports:
      - 8083:8080
    volumes:
      - p3-data:/data
    secrets:
      - setup-vk
      - party-3-sk

volumes:
  p1-data:
  p2-data:
  p3-data:

secrets:
  setup-vk:
    file: ./testdata/setup_vk

  party-1-sk:
    file: ./testdata/party_0_sk

  party-2-sk:
    file: ./testdata/party_1_sk

  party-3-sk:
    file: ./testdata/party_2_sk
