version: "3.8"

services:
  setup-coord:
    image: dkls-party
    command: |
      /usr/local/bin/msg-relay-svc
        --listen 0.0.0.0:8080
    environment: &relay-env
      RUST_LOG: info
    expose:
      - 8080
    ports:
      - 8080:8080


  p-1-coord:
    image: dkls-party
    command: |
      /usr/local/bin/msg-relay-svc
        --listen 0.0.0.0:8080
        --peer ws://setup-coord:8080/v1/msg-relay
        --peer ws://p-2-coord:8080/v1/msg-relay
        --peer ws://p-3-coord:8080/v1/msg-relay
    environment: *relay-env
    expose:
      - 8080

  p-2-coord:
    image: dkls-party
    command: |
      /usr/local/bin/msg-relay-svc
        --listen 0.0.0.0:8080
        --peer ws://setup-coord:8080/v1/msg-relay
        --peer ws://p-1-coord:8080/v1/msg-relay
        --peer ws://p-3-coord:8080/v1/msg-relay
    environment: *relay-env
    expose:
      - 8080

  p-3-coord:
    image: dkls-party
    command: |
      /usr/local/bin/msg-relay-svc
        --listen 0.0.0.0:8080
        --peer ws://setup-coord:8080/v1/msg-relay
        --peer ws://p-1-coord:8080/v1/msg-relay
        --peer ws://p-2-coord:8080/v1/msg-relay
    environment: *relay-env
    expose:
      - 8080

  p-1-1:
    image: dkls-party
    command: |
      /usr/local/bin/dkls-party serve
        --storage /data
        --party-key /run/secrets/party-1-sk
        --setup-vk-file /run/secrets/setup-vk
        --coordinator ws://p-1-coord:8080/v1/msg-relay
    environment: &node-env
      RUST_LOG: info
      RAYON_NUM_THREADS: 3
      TOKIO_WORKER_THREADS: 1
    ports:
      - 8081:8080
    volumes:
      - p1-data:/data
    secrets:
      - setup-vk
      - party-1-sk

  p-2-1:
    image: dkls-party
    command: |
      /usr/local/bin/dkls-party serve
        --storage /data
        --party-key /run/secrets/party-2-sk
        --setup-vk-file /run/secrets/setup-vk
        --coordinator ws://p-2-coord:8080/v1/msg-relay
    environment: *node-env
    ports:
      - 8082:8080
    volumes:
      - p2-data:/data
    secrets:
      - setup-vk
      - party-2-sk

  p-3-1:
    image: dkls-party
    command: |
      /usr/local/bin/dkls-party serve
        --storage /data
        --party-key /run/secrets/party-3-sk
        --setup-vk-file /run/secrets/setup-vk
        --coordinator ws://p-3-coord:8080/v1/msg-relay
    environment: *node-env
    ports:
      - 8083:8080
    volumes:
      - p3-data:/data
    secrets:
      - setup-vk
      - party-3-sk

volumes:
  p1-data:
  p2-data:
  p3-data:

networks:
  p1-int:
  p1-ext:

secrets:
  setup-vk:
    file: ./testdata/setup_vk

  party-1-sk:
    file: ./testdata/party_0_sk

  party-2-sk:
    file: ./testdata/party_1_sk

  party-3-sk:
    file: ./testdata/party_2_sk
