[package]
name = "msg-relay-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
url = { version = "2.3" }
futures-util = { version = "0.3.28" }
tokio = { version = "1.29", features = [ "net" ] }
tokio-tungstenite = { version = "0.20" }
